CLASS zcltbl DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_amdp_marker_hdb .
    CLASS-METHODS :  TBLFUNC FOR TABLE FUNCTION ZTFCDS.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcltbl IMPLEMENTATION.
  METHOD tblfunc BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT USING SFLIGHT.

  RETURN
  SELECT  MANDT , CARRID, CONNID, FLDATE, PRICE FROM SFLIGHT WHERE
    CONTAINS ( CARRID , :AIRLINE , FUZZY );

  ENDMETHOD.

ENDCLASS.
